### ISSUE TITLE
Mailer autodetection undeterministic with new Perl versions

### ISSUE THREAD

**Issue by inva-raritan** [rjbs/Email-Send#3]
I'm maintaining a legacy application that uses Email::Send. After upgrading to a newer version of Perl the script stopped working reliably. This is because Perl 5.18 introduced [Hash order randomization](http://www.perlmonks.org/?node_id=1005122), which causes Email::Send to try the available mailers in random order. If the "Test" mailer is tried before SMTP or Sendmail, the mail is lost.

Please consider adding a note to the documentation, and maybe issuing a warning when Email::Send->new is called without mailer parameter.

**Comment by rjbs** [comment]
The latest Email-Send will decline to use Test when trying "all mailers."  Thanks for this report!
